 - hosts: localhost
   connection: local
   become: true
 
   pre_tasks:
     - name: update repo & upgrade
       apt:
         update_cache: yes
         upgrade: dist
       changed_when: False
   tasks:
     - include: tasks/users.yml
     - include: tasks/cron.yml
     - include: tasks/packages.yml
